pipeline {
    
    agent any
    
    tools {
        maven 'Maven-3.6.3'
    }
    
    stages {
        stage('Build') {
            steps {
                    sh 'mvn clean install'
            }
        }
        
       stage('Run') {
            steps {
                    sh 'java -jar my-app-1.0-SNAPSHOT.jar'
            }
        }

    }
    
    post {
        always {
            cleanWs()
        }   
    }
    
    
}
