pipeline {
    
    agent {
        docker{
            image "maven:3.6.3-jdk-14"
            args '-v /root/.m2:/root/.m2'
        }
    }
    
    stages {
        stage('Build') {
            steps {
                    sh 'mvn clean install'
            }
        }
        
         stage('Deliver') { 
            steps {
                sh './jenkins/scripts/deliver.sh' 
            }
        }
        


    }
    
  
    
    
}
